#!/bin/bash

# This file is automatically generated by podFiles deploy tool.
# DO NOT EDIT THIS FILE DIRECTLY.
# See: https://github.com/zrcoder/podFiles/tree/main/cmd/deploy

set -e 

usage() {
    cat << HELP
Install podFiles service to Kubernetes cluster.

Usage: 
    $0 <namespace> <image> <domain>

Arguments:
    namespace   The namespace to deploy podFiles
    image       The Docker image for podFiles service
    domain      The domain name for ingress

Example:
    $0 xxx podfiles:latest podfiles.example.com

Options:
    -h, --help  Show this help message
HELP
    exit 0
}

# 处理帮助参数
case "$1" in
    -h|--help)
        usage
        ;;
esac

if [ -z "$3" ]; then
    echo "Error: Missing required arguments"
    echo
    usage
    exit 1
fi

NAMESPACE=$1
IMAGE=$2
DOMAIN=$3

echo "Installing podFiles with:"
echo "  Namespace: $NAMESPACE"
echo "  Image: $IMAGE"
echo "  Domain: $DOMAIN"

kubectl get namespace $NAMESPACE > /dev/null 2>&1 || kubectl create namespace $NAMESPACE

echo "Applying cluster resources for namespace: $NAMESPACE"
cat << 'EOF' | NAMESPACE=$NAMESPACE envsubst | kubectl apply -f -
{{ .ClusterResources }}
EOF

echo "Applying namespace resources in namespace: $NAMESPACE"
cat << 'EOF' | IMAGE=$IMAGE DOMAIN=$DOMAIN envsubst | kubectl -n $NAMESPACE apply -f -
{{ .NamespaceResources }}
EOF

echo "✅ Deployment completed successfully"