# RBAC Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podfiles-role
rules:
  - apiGroups: [""]
    resources:
      - "namespaces"
      - "pods"
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
# RBAC RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podfiles-role-binding
subjects:
  - kind: ServiceAccount
    name: podfiles-sa
    namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: podfiles-role
  apiGroup: rbac.authorization.k8s.io
